general:
  data_base_dir: /app/data
  version: 1.0.0
  description: TotalSegmentator default config (dicom to dicom)

execute:
- DicomImporter
- NiftiConverter
- TotalSegmentatorMLRunner
- DsegConverter
- DataOrganizer

segdb:
  triplets:
    C_BODY_STRUCTURE:
      code: custom
  segments:
    thyroid_gland:
      name: thyroid_gland
      category: C_BODY_STRUCTURE
    vertebrae_S1:
      name: vertebrae_S1
      category: C_BODY_STRUCTURE
    pulmonary_vein:
      name: pulmonary_vein
      category: C_BODY_STRUCTURE
    brachiocephalic_trunk:
      name: brachiocephalic_trunk
      category: C_BODY_STRUCTURE
    subclavian_artery_right:
      name: subclavian_artery_right
      category: C_BODY_STRUCTURE
    subclavian_artery_left:
      name: subclavian_artery_left
      category: C_BODY_STRUCTURE
    common_carotid_artery_right:
      name: common_carotid_artery_right
      category: C_BODY_STRUCTURE
    common_carotid_artery_left:
      name: common_carotid_artery_left
      category: C_BODY_STRUCTURE
    brachiocephalic_vein_left:
      name: brachiocephalic_vein_left
      category: C_BODY_STRUCTURE
    brachiocephalic_vein_right:
      name: brachiocephalic_vein_right
      category: C_BODY_STRUCTURE
    atrial_appendage_left:
      name: atrial_appendage_left
      category: C_BODY_STRUCTURE
    spinal_cord:
      name: spinal_cord
      category: C_BODY_STRUCTURE
    skull:
      name: skull
      category: C_BODY_STRUCTURE
    sternum:
      name: sternum
      category: C_BODY_STRUCTURE
    costal_cartilages:
      name: costal_cartilages
      category: C_BODY_STRUCTURE

modules:
  DicomImporter:
    source_dir: input_data
    import_dir: sorted_data
    sort_data: true
    meta:  
      mod: '%Modality'

  TotalSegmentatorMLRunner:
    use_fast_mode: true

  DsegConverter:
    model_name: TotalSegmentator2
    body_part_examined: WHOLEBODY
    source_segs: nifti:mod=seg
    skip_empty_slices: True
  
  DataOrganizer:
   targets:
   - dicomseg:mod=seg-->[i:sid]/TotalSegmentator2.seg.dcm
   - nifti:mod=ct-->[i:sid]/image.nii.gz
