general:
  data_base_dir: /app/data
  version: 1.0
  description: default configuration for Bamf NNUnet Lung, Nodules and Tumor segmentation (dicom to dicom)

execute:
- DicomImporter
- NiftiConverter
- module: NNUnetRunner
  nnunet_task: Task777_CT_Nodules
  roi: LUNG+NODULE
- module: NNUnetRunner
  nnunet_task: Task775_CT_NSCLC_RG
  roi: LUNG,LUNG+NEOPLASM_MALIGNANT_PRIMARY
- CustomNNUnetRunner
- LungPostProcessor
- DsegConverter
- DataOrganizer

modules:
  DicomImporter:
    source_dir: input_data
    import_dir: sorted_data
    sort_data: true
    meta: 
      mod: '%Modality'

  NNUnetRunner:
    in_data: nifti:mod=ct
    nnunet_model: 3d_fullres
    export_prob_maps: False

  LungPostProcessor:
    in_rg_data: nifti:mod=seg:nnunet_task=Task775_CT_NSCLC_RG
    in_nodules_data: nifti:mod=seg:nnunet_task=Task777_CT_Nodules

  DsegConverter:
    model_name: Bamf NNUnet CT Lung  
    target_dicom: dicom:mod=ct
    source_segs: nifti:mod=seg:processor=bamf
    skip_empty_slices: True

  DataOrganizer:
    targets:
    - dicomseg-->[i:sid]/bamf_nnunet_ct_lung.seg.dcm