general:
  data_base_dir: /app/data
  version: 1.0
  description: "FMCIB pipeline starting from a nii.gz file image and a binary mask of the GTV."

execute:
- FileStructureImporter
- CentroidExtractor
- FMCIBRunner
- DataOrganizer

modules:
  FileStructureImporter:
    structures:
      - $patientID/CT.nii.gz@instance@nifti:mod=ct
      - $patientID/masks/GTV.nii.gz@nifti:mod=seg
    import_id: patientID

  DataOrganizer:
    targets:
      - csv-->[i:patientID]/features.csv

sample:
  input:
    lung_001/CT.nii.gz: A nifti file named containing the CT image per instance
    lung_001/masks/GTV.nii.gz: A nifti file with a binary gtv label map which center is used as seed point
  output:
    lung_001/features.csv: The CSV file containing a set of features extracted from the input CT image
