general:
  data_base_dir: /app/data
  version: 1.0
  description: run pyradiomics pipeline on dicom data

execute:
- DicomImporter
- RTStructExtractor
- NiftiConverter
- CentroidExtractor
- FMCIBRunner
- DataOrganizer

modules:
  DicomImporter:
    source_dir: input_data
    import_dir: sorted_data
    sort_data: true
    merge: true
    meta: 
      mod: '%Modality'
      desc: '%SeriesDescription'

  # roi can be specified manually but will otherwise extracted form the rtstruct segemnetation names
  # RTStructExtractor:
  #   roi: 
  #   - LIVER
  #   - LIVER+NEOPLASM_MALIGNANT_PRIMARY

  DataOrganizer:
    targets:
      - csv-->[i:sid]/features.csv
        # - nifti-->[i:sid]/nifti/[d:mod]/[basename]

sample:
  input:
    SEG_1.2.276.0.7230010.3.1.3.8323329.7977.1556876807.594745/: Input directory containing
      the dicom segmentation file 
    RTSTRUCT_1.2.246.352.71.2.494841863751.4253616.20190218155318/: Input directory
      containing the RTSTRUCT_1.2.246.352.71.2.494841863751.4253616.20190218155318
      image
    CT_1.3.6.1.4.1.9590.100.1.2.170217758912108379426621313680109428629/: Input directory
      containing the CT_1.3.6.1.4.1.9590.100.1.2.170217758912108379426621313680109428629
      image
  output:
    1.3.6.1.4.1.9590.100.1.2.170217758912108379426621313680109428629/features.csv: The CSV file containing a set of features extracted from the input CT image
