general:
  data_base_dir: /app/data
  version: 1.0
  description: "FMCIB pipeline starting from a nii.gz file image and a binary mask of the GTV."

execute:
- FileStructureImporter
- CentroidExtractor
- FMCIBRunner
- DataOrganizer

modules:
  FileStructureImporter:
    structures:
      - $patientID/CT.nii.gz@instance@nifti:mod=ct
      - $patientID/masks/GTV.nii.gz@nifti:mod=seg
    import_id: patientID

  DataOrganizer:
    targets:
      - csv-->[i:patientID]/features.csv
