general:
  data_base_dir: /app/data
  version: 1.0
  description: "FMCIB pipeline starting from a coordinate json file"

execute:
- FileStructureImporter
- FMCIBRunner
- DataOrganizer

modules:
  FileStructureImporter:
    structures:
      - $patientID/CT.nrrd@instance@nrrd:mod=ct
      - $patientID/centroids.json@json:type=fmcibcoordinates
    import_id: patientID

  DataOrganizer:
    targets:
      - json:type=fmcibfeatures-->[i:patientID]/features.json