general:
  data_base_dir: /app/data
  version: 1.0
  description: default configuration for Bamf NNUnet Breast FDG-avid lesions segmentation (dicom to dicom)

execute:
- FileStructureImporter
- NiftiConverter
- Registration
- NNUnetPETCTRunner
- TotalSegmentatorMLRunner
- BreastPostProcessor
- DsegConverter
- DataOrganizer

modules:

  FileStructureImporter:
    input_dir: 'input_data'
    structures:
      - $patientID@instance/ct@dicom:mod=ct
      - $patientID/pt@dicom:mod=pt
    import_id: patientID

  NiftiConverter:
    in_datas: dicom:mod=ct|pt
    engine: dcm2niix
    allow_multi_input: true

  TotalSegmentatorMLRunner:
    in_data: nifti:mod=ct:registered=true
    use_fast_mode: true

  NNUnetPETCTRunner:
    in_ct_data: nifti:mod=ct:registered=true

  BreastPostProcessor:
    in_ct_data: nifti:mod=ct:registered=true

  DsegConverter:
    source_segs: nifti:mod=seg:processor=bamf
    model_name: BAMF Breast and Tumor AI Segmentation
    target_dicom: dicom:mod=pt
    skip_empty_slices: True

  DataOrganizer:
    targets:
    - dicomseg-->[i:patientID]/bamf_pet_ct_breast_tumor.seg.dcm

sample:
  idc:
    "p1/ct": 
      SeriesInstanceUID: 1.3.6.1.4.1.14519.5.2.1.8162.7003.539267076861125410814830191835
      aws_url: s3://idc-open-data/84c9b972-76e1-4fa3-a7ea-19b6500e497a/*
    "p1/pt": 
      SeriesInstanceUID: 1.3.6.1.4.1.14519.5.2.1.8162.7003.196821690630879561473146713439
      aws_url: s3://idc-open-data/33f0bd14-4bf5-469c-83db-183e1ab96f02/*
  input:
    "p1": "Folder containing one case / patient, e.g., named after the patient identifyer"
    "p1/ct/": "Folder containing dicom files for the CT scan of the patient to be analysed"
    "p1/pt/": "Folder containing dicom files for an associated PET scan"
  output:
    "p1/bamf_pet_ct_breast_tumor.seg.dcm": "Segmentation output file"
