general:
  data_base_dir: /app/data
  version: 1.0
  description: "Default configuration for LungMask (dicom in, dicom out)"

execute:
- DicomImporter
- NiftiConverter
- LungMaskRunner
- DsegConverter
- DataOrganizer

modules:
  DicomImporter:
    source_dir: input_data
    import_dir: sorted_data
    sort_data: True
    meta: 
      mod: '%Modality'

  LungMaskRunner:
    batchsize: 64

  DsegConverter:
    model_name: LungMask
    body_part_examined: CHEST
    source_segs: nifti:mod=seg:roi=*
    skip_empty_slices: True
  
  DataOrganizer:
    targets:
    - dicomseg:mod=seg-->[i:sid]/lungmask.seg.dcm
