general:
  data_base_dir: /app/data
  version: 1.0.0
  description: MRSegmentator default config (dicom to dicom)

execute:
- DicomImporter
- NiftiConverter
- MRSegmentatorMLRunner
- DsegConverter
- DataOrganizer

modules:
  DicomImporter:
    source_dir: input_data
    import_dir: sorted_data
    sort_data: true
    meta: 
      mod: '%Modality'

  MRSegmentatorMLRunner:

  DsegConverter:
    model_name: MRSegmentator
    body_part_examined: WHOLEBODY
    source_segs: nifti:mod=seg
    skip_empty_slices: True
    target_dicom: dicom:mod=ct|mr
  
  DataOrganizer:
   targets:
   - dicomseg:mod=seg-->[i:sid]/MRSegmentator.seg.dcm
