general:
  data_base_dir: /app/data
  version: 1.0
  description: default configuration for Bamf CT Liver and tumor segmentation (dicom to dicom)

execute:
- DicomImporter
- NiftiConverter
- NNUnetRunnerV2
- PostProcessor
- DsegConverter
- DataOrganizer

modules:
  DicomImporter:
    source_dir: input_data
    import_dir: sorted_data
    sort_data: true
    meta: 
      mod: '%Modality'

  NNUnetRunnerV2:
    in_data: nifti:mod=ct
    nnunet_dataset: Dataset006_Liver
    nnunet_config: 3d_fullres
    roi: SPLEEN,KIDNEY,GALLBLADDER,DUODENUM,PANCREAS,SMALL_INTESTINE,LUNG,LIVER,LIVER+NEOPLASM_MALIGNANT_PRIMARY
    export_prob_maps: False

  DsegConverter:
    model_name: bamf_ct_liver_tumor
    target_dicom: dicom:mod=ct
    source_segs: nifti:mod=seg:processor=bamf
    skip_empty_slices: True

  DataOrganizer:
    targets:
    - dicomseg-->[i:sid]/bamf_ct_liver_tumor.seg.dcm    