"""
---------------------------------------------------------
Mhub / DIAG - Run Module for resampling FDG CT to FDG PET
---------------------------------------------------------

---------------------------------------------------------
Author: Sil van de Leemput
Email:  sil.vandeleemput@radboudumc.nl
---------------------------------------------------------
"""

import pyplastimatch as pypla

from mhubio.core import Instance, InstanceData, IO, Module


class FDGPETCTResampleProcessor(Module):

    @IO.Instance()
    @IO.Input('in_data_ct', 'nifti:mod=ct', the='input FDG CT scan')
    @IO.Input('in_data_pet', 'nifti:mod=pt', the='input FDG PET scan')
    @IO.Output('out_data_ct', 'CTres.nii.gz', 'nifti:mod=ct:resampled=true', bundle='registered', the='Converted CT image resampled to PET image resolution and size')
    @IO.Output('out_log_data', 'pmresample.log', 'log:log-task=resampling', the="log generated by plastimatch for the resampling operation")
    def task(self, instance: Instance, in_data_ct: InstanceData, in_data_pet: InstanceData, out_data_ct: InstanceData, out_log_data: InstanceData) -> None:
        resample_args = {
            'input': in_data_ct.abspath,
            'output': out_data_ct.abspath,
            'fixed': in_data_pet.abspath,
            'default-value': str(-1024)
        }

        pypla.resample(
           verbose=self.config.verbose,
           path_to_log_file=out_log_data.abspath,
           **resample_args
        )
