general:
  data_base_dir: /app/data
  version: 1.0
  description: Default configuration for Bamf NNUnet Breast and tumor segmentation on MR scans (dicom to dicom)

execute:
- DicomImporter
- NiftiConverter
- module: NNUnetRunnerV2
  nnunet_dataset: Dataset009_Breast
  roi: BREAST,BREAST+BREAST_FIBROGLANDULAR_TISSUE
- module: NNUnetRunnerV2
  nnunet_dataset: Dataset011_Breast
  roi: BREAST+BREAST_CARCINOMA
- BreastPostProcessor
- DsegConverter
- DataOrganizer

modules:
  DicomImporter:
    source_dir: input_data
    import_dir: sorted_data
    sort_data: true
    meta: 
      mod: '%Modality'

  NNUnetRunnerV2:
    in_data: nifti:mod=mr

  BreastPostProcessor:
    in_breast_data: nifti:mod=seg:nnunet_task=Dataset009_Breast
    in_tumor_data: nifti:mod=seg:nnunet_task=Dataset011_Breast

  DsegConverter:
    model_name: BAMF Breast and Tumor AI Segmentation
    target_dicom: dicom:mod=mr
    source_segs: nifti:mod=seg:processor=bamf
    skip_empty_slices: True

  DataOrganizer:
    targets:
    - dicomseg-->[i:sid]/bamf_nnunet_mr_breast.seg.dcm
