general:
  data_base_dir: /app/data
  version: 1.0
  description: Default configuration for Bamf NNUnet Breast and tumor segmentation on MR scans (dicom to dicom)

segdb:
  triplets:
    T_BREAST_FGT_STRUCTURE:
      code: 1342375003
      meaning: Structure of fibroglandular tissue of breast
      scheme_designator: SCT
    T_BREAST_CARCINOMA_MASS:
      code: 4147007
      meaning: Mass
      scheme_designator: SCT
  segments:
    FGT:
      name: FGT
      category: C_RADIOLOGIC_FINDING
      type: T_BREAST_FGT_STRUCTURE
      color: [128, 174, 128]
    BREAST_CARCINOMA:
      name: Breast_Carcinoma
      category: C_MORPHOLOGICALLY_ABNORMAL_STRUCTURE
      type: T_BREAST_CARCINOMA_MASS
      modifier: M_RIGHT_AND_LEFT
      color: [144, 238, 144]

execute:
- DicomImporter
- NiftiConverter
- module: NNUnetRunnerV2
  nnunet_dataset: Dataset009_Breast
  roi: BREAST,BREAST+FGT
- module: NNUnetRunnerV2
  nnunet_dataset: Dataset011_Breast
  roi: BREAST+BREAST_CARCINOMA
- BreastPostProcessor
- DsegConverter
- DataOrganizer

modules:
  DicomImporter:
    source_dir: input_data
    import_dir: sorted_data
    sort_data: true
    meta: 
      mod: '%Modality'

  NNUnetRunnerV2:
    in_data: nifti:mod=mr

  BreastPostProcessor:
    in_breast_data: nifti:mod=seg:nnunet_task=Dataset009_Breast
    in_tumor_data: nifti:mod=seg:nnunet_task=Dataset011_Breast

  DsegConverter:
    model_name: Bamf NNUnet MR Breast and tumor
    target_dicom: dicom:mod=mr
    source_segs: nifti:mod=seg:processor=bamf
    skip_empty_slices: True

  DataOrganizer:
    targets:
    - dicomseg-->[i:sid]/bamf_nnunet_mr_breast.seg.dcm
