general:
  data_base_dir: /app/data
  version: 1.0
  description: Default configuration for Bamf NNUnet Breast and tumor segmentation on MR scans (dicom to dicom)

segdb:
  triplets:
    BREAST_FGT_TRIPLET:
      code: 123
      meaning: breast and fgt triplets
  segmentations:
    BREAST:
      name: custom label and color for breast segmentation
      category: C_BODY_STRUCTURE
      type: T_BREAST_STRUCTURE
      color: [255, 0, 0]
    FGT:
      name: custom label and color for fibrograndular tissue segmentation
      category: C_BODY_STRUCTURE
      type: T_BREAST_STRUCTURE
      color: [0, 255, 0]

execute:
- DicomImporter
- NiftiConverter
- module: NNUnetRunnerV2
  nnunet_dataset: Dataset009_Breast
  roi: BREAST,FGT
- module: NNUnetRunnerV2
  nnunet_dataset: Dataset011_Breast
  roi: BREAST+TUMOR
- BreastPostProcessor
- DsegConverter
- DataOrganizer

modules:
  DicomImporter:
    source_dir: input_data
    import_dir: sorted_data
    sort_data: true
    meta: 
      mod: '%Modality'

  NNUnetRunnerV2:
    in_data: nifti:mod=mr
    nnunet_config: 3d_fullres
    export_prob_maps: False

  BreastPostProcessor:
    in_breast_data: nifti:mod=seg:nnunet_task=Dataset009_Breast
    in_tumor_data: nifti:mod=seg:nnunet_task=Dataset011_Breast

  DsegConverter:
    model_name: Bamf NNUnet MR Breast and tumor
    target_dicom: dicom:mod=mr
    source_segs: nifti:mod=seg:processor=bamf
    skip_empty_slices: True

  DataOrganizer:
    targets:
    - dicomseg-->[i:sid]/bamf_nnunet_mr_breast.seg.dcm
