general:
  data_base_dir: /app/data
  
modules:
  DicomImporter:
    source_dir: input_data
    import_dir: sorted_data
    sort_data: True
    meta: 
      mod: ct
   
  LobeSegmentationRunner:

  DsegConverter:
    dicomseg_json_path: /app/models/xie2020_lobe_segmentation/config/dseg.json
    skip_empty_slices: True
    body_part_examined: LUNG
    source_segs: ['mha:mod=seg:roi=*']
