general:
  data_base_dir: /app/data
  version: 1.0.0
  description: Default configuration for SMIT model (dicom to dicom)

execute:
- DicomImporter
- NiftiConverter
- SMITRunner
- DsegConverter
- DataOrganizer

modules:
  DicomImporter:
    source_dir: input_data
    import_dir: sorted_data
    sort_data: true
    meta: 
      mod: '%Modality'

  NiftiConverter:
    engine: dcm2niix

  DsegConverter:
    model_name: SMIT
    body_part_examined: CHEST
    source_segs: nifti:mod=seg
    skip_empty_slices: true
  
  DataOrganizer:
   targets:
   - dicomseg:mod=seg-->[i:sid]/msk_smit_lung_gtv.seg.dcm
   
sample:
  input:
    dicom/: Folder with DICOM files of one or more CT scans.
  output:
    1.3.6.1.4.1.14519.5.2.1.7311.5101.160028252338004527274326500702/msk_smit_lung_gtv.seg.dcm: The DICOM SEG file with Lung GTV segmentation (arbitrary series ID foldername).
