general:
  data_base_dir: /app/data
  version: 1.0
  description: default configuration for Bamf NNUnet FDG-Avid Breast Tumor segmentation (dicom to dicom)

execute:
- FileStructureImporter
- NiftiConverter
- Resampler
- NNUnetPETCTRunner
- TotalSegmentatorMLRunner
- BreastPostProcessor
- DsegConverter
- DataOrganizer

modules:
  FileStructureImporter:
    input_dir: 'input_data'
    structures:
      - $patientID@instance/CT@dicom:mod=ct
      - $patientID/PT@dicom:mod=pt
    import_id: patientID

  NiftiConverter:
    in_datas: dicom:mod=pt|ct
    allow_multi_input: true

  NNUnetPETCTRunner:
    nnunet_task: Task762_PET_CT_Breast
    nnunet_model: 3d_fullres
    roi: NEOPLASM_MALIGNANT_PRIMARY
    folds: 0

  TotalSegmentatorMLRunner:
    use_fast_mode: true

  DsegConverter:
    source_segs: nifti:mod=seg:processor=bamf
    model_name: BAMF Breast FDG PET CT
    target_dicom: dicom:mod=ct
    skip_empty_slices: True

  DataOrganizer:
    targets:
    - dicomseg-->[i:patientID]/bamf_nnunet_ct_breast.seg.dcm