general:
  data_base_dir: /app/data
  version: 1.0
  description: default configuration for Bamf NNUnet Lung and FDG-avid lesions in the lung from FDG PET/CT scans (dicom to dicom)

execute:
- FileStructureImporter
- NiftiConverter
- Registration
- NNUnetPETCTRunner
- TotalSegmentatorMLRunner
- LungPostProcessor
- DsegConverter
- DataOrganizer

modules:
  FileStructureImporter:
    input_dir: 'input_data'
    structures:
      - $patientID@instance/CT@dicom:mod=ct
      - $patientID/PT@dicom:mod=pt
    import_id: patientID

  NiftiConverter:
    in_datas: dicom:mod=pt|ct
    allow_multi_input: true

  NNUnetPETCTRunner:
    in_ct_data: nifti:mod=ct:registered=true
    nnunet_task: Task762_PET_CT_Breast
    nnunet_model: 3d_fullres
    roi: LIVER,RIGHT_KIDNEY,URINARY_BLADDER,SPLEEN,LUNG,BRAIN,LEFT_ATRIUM,SMALL_INTESTINE,FDG_AVID_TUMOR

  TotalSegmentatorMLRunner:
    in_data: nifti:mod=ct:registered=true
    use_fast_mode: true

  LungPostProcessor:
    in_ct_data: nifti:mod=ct:registered=true

  DsegConverter:
    source_segs: nifti:mod=seg:processor=bamf
    model_name: BAMF Lung FDG PET CT
    target_dicom: dicom:mod=ct
    skip_empty_slices: True

  DataOrganizer:
    targets:
    - dicomseg-->[i:patientID]/bamf_nnunet_pet_ct_lung.seg.dcm